version: '3'

services:
  websole:
    build: ./express-app
    env_file:
      - express-app/.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
  db:
    image: mongo
    restart: always
     